export const UPDATE_ALL_DOCUMENT = 'UPDATE_ALL_DOCUMENT' as const

export const UPDATE_CURRENT_DOCUMENT = 'UPDATE_CURRENT_DOCUMENT' as const

export const TOGGLE_DOCUMENT = 'TOGGLE_DOCUMENT' as const

export const NAVIGATE_HOME = 'NAVIGATE_HOME' as const

export const ADD_DOCUMENT_FROM_PARENT_DOCUMENT = 'ADD_DOCUMENT_FROM_PARENT_DOCUMENT' as const
