export const FETCH_ALL_DOCUMENT = 'FETCH_ALL_DOCUMENT' as const

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR' as const

export const VISIT_HOME = 'VISIT_HOME' as const

export const CREATE_DOCUMENT_FROM_PARENT_DOCUMENT = 'CREATE_DOCUMENT_FROM_PARENT_DOCUMENT' as const

export const VISIT_MAIN_PAGE = 'VISIT_MAIN_PAGE' as const
